name: Rust test (Cargo)

on:
  workflow_dispatch:
    inputs:
      RS_FILE:
        description: Name of the RS file (without the .RS extension)
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Cargo init
      run: |
        cargo init "${{ inputs.RS_FILE }}"
        mv "${{ inputs.RS_FILE }}".rs "${{ inputs.RS_FILE }}"/src/main.rs
        printf "\nFiles\n"
        find "${{ inputs.RS_FILE }}"|grep -v "${{ inputs.RS_FILE }}/.git/"
    - name: Cargo Build
      run: cargo build --verbose
    - name: Cargo Test
      run: cargo test --verbose
