name: Run tests using cargo

on:
  workflow_dispatch:
    inputs:
      RS_FILE:
        description: Name of the RS file (without the .RS extension)
        required: true
        type: string

      DO_RUN:
        description: Perform a cargo run instead of a test
        required: true
        type: boolean
        default: false


env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo
      uses: actions/checkout@v3
    - name: Run cargo init
      run: |
        cargo init --vcs=none "${{ inputs.RS_FILE }}"
        mv "${{ inputs.RS_FILE }}".rs "${{ inputs.RS_FILE }}"/src/main.rs
        rm *.rs
        mv "${{ inputs.RS_FILE }}"/* ./
        rmdir "${{ inputs.RS_FILE }}"
        printf "\nFiles\n"
        find ./"${{ inputs.RS_FILE }}"/|grep -v "^./.git"
    - name: Run cargo build
      run: cargo build --verbose
    - name: Run cargo test (or run)
      run: |
        COND=${{ inputs.DO_RUN }}
        if [ $COND == true ]
        then
          echo "Program output is below this line"
          cargo run --verbose
        fi
        if [ $COND == false ]
        then
          echo "Test results are below this line"
          cargo test --verbose
        fi
