name: Run tests using cargo

on:
  workflow_dispatch:
    inputs:
      RS_FILE:
        description: Name of the RS file (without the .RS extension)
        required: true
        type: string

      DO_RUN:
        description: Perform a cargo run instead of a test
        required: true
        type: bool
        default: false


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Cargo init
      run: |
        cargo init --vcs=none "${{ inputs.RS_FILE }}"
        mv "${{ inputs.RS_FILE }}".rs "${{ inputs.RS_FILE }}"/src/main.rs
        mv "${{ inputs.RS_FILE }}"/* ./
        rmdir "${{ inputs.RS_FILE }}"
        printf "\nFiles\n"
        find ./|grep -v "^./.git"
    - name: Cargo Build
      run: cargo build --verbose
    - name: Cargo Test
      run: |
        if [ {{ inputs.DO_RUN }} == true ]
        then
          cargo run --verbose
        fi
        if [ {{ inputs.DO_RUN }} == false ]
        then
          cargo test --verbose
        fi
